name: Fetch Alignment Research Dataset

on:
  workflow_dispatch: # allow manual triggering

jobs:
  fetch-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    strategy:
      matrix:
        datasource:
          - agentmodels
          - aiimpacts.org
          - aipulse.org
          - aisafety.camp
          - alignment_newsletter
          - arbital
          - arxiv_papers
          - audio_transcripts
          - carado.moe
          - cold.takes
          - deepmind.blog
          - distill
          - eaforum
          - gdocs
          - gdrive_ebooks
          - generative.ink
          - gwern_blog
          - intelligence.org
          - jsteinhardt.wordpress.com
          - lesswrong
          - markdown.ebooks
          - nonarxiv_papers
          - qualiacomputing.com
          - reports
          - stampy
          - vkrakovna.wordpress.com
          - waitbutwhy
          - yudkowsky.net
